apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: udagram-api-feed
  name: udagram-api-feed
spec:
  replicas: 2
  selector:
    matchLabels:
      service: udagram-api-feed
  strategy: {}
  template:
    metadata:
      labels:
        service: udagram-api-feed
    spec:
      containers:
        - env:
            - name: AWS_BUCKET
              valueFrom:
                configMapKeyRef:
                  name: my-configmap
                  key: AWS_BUCKET
            - name: AWS_REGION
              valueFrom:
                configMapKeyRef:
                  name: my-configmap
                  key: AWS_REGION
            - name: JWT_SECRET
              valueFrom:
                configMapKeyRef:
                  name: my-configmap
                  key: JWT_SECRET
            - name: URL
              valueFrom:
                configMapKeyRef:
                  name: my-configmap
                  key: URL
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: my-configmap
                  key: POSTGRES_HOST
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: my-configmap
                  key: POSTGRES_DB
            - name: POSTGRES_USERNAME
              valueFrom:
                secretKeyRef:
                  name: my-postgres-secret
                  key: postgres_username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: my-postgres-secret
                  key: postgres_password
            - name: AWS_PROFILE
              valueFrom:
                secretKeyRef:
                  name: my-aws-secret
                  key: aws_profile
            - name: AWS_SECRET_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: my-aws-secret
                  key: aws_secret_key_id
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: my-aws-secret
                  key: aws_secret_access_key
          image: olusoladeboy/udagram-api-feed:v1
          name: udagram-api-feed
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "5000Mi"
              cpu: "500m"
            limits:
              memory: "5000Mi"
              cpu: "500m"
      restartPolicy: Always
status: {}
