apiVersion: apps/v1
kind: Deployment
metadata:
  name: reverseproxy
spec:
  selector:
    matchLabels:
      run: reverseproxy
  replicas: 2
  template:
    metadata:
      labels:
        run: reverseproxy
    spec:
      containers:
        - name: reverseproxy
          image: olusoladeboy/reverseproxy:v1
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "256m"
            limits:
              cpu: "512m"
